import { Hono } from "hono";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
import { requestId } from "hono/request-id";
import { initSentry } from "./lib/sentry.js";
import { errorHandler } from "./middlewares/error-handler.js";
import { asistenciaRoutes, portalAsistenciaRoutes } from "./modules/asistencia/http/routes.js";
import { authRoutes } from "./modules/auth/http/routes.js";
import { cajaRoutes } from "./modules/cajas/http/routes.js";
import { categoriaRoutes } from "./modules/categorias/http/routes.js";
import { clienteRoutes } from "./modules/clientes/http/routes.js";
import { componenteRoutes } from "./modules/componentes/http/routes.js";
import { cotizacionCompraRoutes } from "./modules/cotizaciones-compra/http/routes.js";
import { cotizacionVentaRoutes } from "./modules/cotizaciones-venta/http/routes.js";
import { crmRoutes } from "./modules/crm/http/routes.js";
import { domicilioRoutes } from "./modules/domicilios/http/routes.js";
import { featureFlagRoutes } from "./modules/feature-flags/http/routes.js";
import { healthRoutes } from "./modules/health/routes.js";
import { inventarioRoutes } from "./modules/inventario/http/routes.js";
import { marcaRoutes } from "./modules/marcas/http/routes.js";
import { modeloRoutes } from "./modules/modelos/http/routes.js";
import { ordenCompraRoutes } from "./modules/ordenes-compra/http/routes.js";
import { pagoProveedorRoutes } from "./modules/pagos-proveedor/http/routes.js";
import { portalRoutes } from "./modules/portal/http/routes.js";
import { proveedorRoutes } from "./modules/proveedores/http/routes.js";
import { serviciosRoutes } from "./modules/servicios/http/routes.js";
import { solicitudCompraRoutes } from "./modules/solicitudes-compra/http/routes.js";
import { sucursalRoutes } from "./modules/sucursales/http/routes.js";
import { usuarioRoutes } from "./modules/usuarios/http/routes.js";
import { ventaRoutes } from "./modules/ventas/http/routes.js";
import type { HonoVariables } from "./types/context.js";

initSentry();

export const app = new Hono<{ Variables: HonoVariables }>();

app.use(cors());
app.use(requestId());
app.use(logger());
app.onError(errorHandler);

app.route("/api/v1", healthRoutes);
app.route("/api/v1", authRoutes);
app.route("/api/v1", usuarioRoutes);
app.route("/api/v1", sucursalRoutes);
app.route("/api/v1", featureFlagRoutes);
app.route("/api/v1", clienteRoutes);
app.route("/api/v1", categoriaRoutes);
app.route("/api/v1", componenteRoutes);
app.route("/api/v1", marcaRoutes);
app.route("/api/v1", modeloRoutes);
app.route("/api/v1", inventarioRoutes);
app.route("/api/v1", proveedorRoutes);
app.route("/api/v1", cotizacionCompraRoutes);
app.route("/api/v1", solicitudCompraRoutes);
app.route("/api/v1", ordenCompraRoutes);
app.route("/api/v1", pagoProveedorRoutes);
app.route("/api/v1", serviciosRoutes);
app.route("/api/v1", cajaRoutes);
app.route("/api/v1", ventaRoutes);
app.route("/api/v1", cotizacionVentaRoutes);
app.route("/api/v1", domicilioRoutes);
app.route("/api/v1", portalRoutes);
app.route("/api/v1", crmRoutes);
app.route("/api/v1", asistenciaRoutes);
app.route("/api/v1", portalAsistenciaRoutes);

export type AppType = typeof app;
